server:
  port: 28019
spring:
  flyway:
    enabled: true
    locations: ["classpath:db/migration"]
  datasource:
    url: jdbc:mysql://localhost:3306/newbee_mall?useUnicode=true&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
