spring:
  flyway:
    enabled: true
    locations: [ "classpath:db/migration" ]
  datasource:
    url: jdbc:mysql://localhost:3306/newbee_mall?useUnicode=true&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
server:
  servlet:
    context-path: /api/v1
